{% set xorg_name = "libxcb" %}
{% set xorg_category = "xcb" %}
{% set name = "libxcb" %}
{% set version = "1.13" %}
{% set sha256 = "188c8752193c50ff2dbe89db4554c63df2e26a2e47b0fa415a70918b5b851daa" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - windows.patch  # [win]

build:
  skip: True  # [osx]
  number: 2
  detect_binary_files_with_prefix: true
  number: 3
  features:
    - vc{{ vc }}  # [win]
  run_exports:
    #  Excellent: only new symbols
    #   https://abi-laboratory.pro/tracker/timeline/libxcb/
    - {{ pin_subpackage('libxcb') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('xorg-x11-util-macros') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - m2w64-toolchain  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - xcb-proto
    - pthread-stubs

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: "This is the C-language Binding (XCB) package to the X Window System protocol"

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw
