travis:
  secure:
    BINSTAR_TOKEN: W7V9LIfo0p/MUQnwDAQCBK/AigXohD6hBip1lV3lvkX3ixYeGcV9AHK+o2SremEVxge9+FEuOiGHTSh/ppkF8Z2O5eQ6Z3/7JR7ue7kTQgkRkB8xGOKxVdLjZ7yfsyA1tkekZMeLjRyS1f5wRhrIREF4h73uZq/T7xtmu0m4b2hrqXRzlDTWTvkzZLK2C9OmCooZUMtndTtOEP2AJKlXKmQWEUmQSgKkXFzF8cI6gj4pT13utszR78QfjuA7kws3F7QyD7C3gXaHqxm8XQYgMbzOPC9JG6Nv1krnZYlleKcc7BGCYTpIhCDZpJ/Qq0jScZmS8h9vxowRFv5XSPS0pvSxZqg7zv98RrLy/bp5xLZD8UgMUnCbDIVl40agiYzzObw4X9Vl6BM9ezvfwg8AXJYnfkbcHZgVGA0tCRoZnmqnPRM0UQ6a/LtHfzI1bqqY1fnhmT6Xrw8sREVTIzyfpCvVQfPHnwQ3sIVGF6PSmaXTXMznQZF8n86DRBweh0iTociuJlePquZWgYvr2q5HtdqANzlKLD19UHTDnXQS8DC+CcdeB2oaJjQvqn91gQT4vti5AX74/FjyAgrToKVDoK9mDVI0yA+3t9brDf/nq1x+aPS2Vwn/F1uZoOIqyIy2MFK2Dw46aAhVl6ga/UAHvk7sGAo5yEyXMIpFFm5B6kg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
